- name: variables from files level
  hosts: localhost
  vars_files:
  - vars1.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "hi am learing {{course}}, my name is {{student}} ,duration is {{duration}}"